spring:
  kafka:
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='${vcap.services.kafka.credentials.username}' password='${vcap.services.kafka.credentials.password}';"
    bootstrap-servers: "${vcap.services.kafka.credentials.bootstrap}:9092"
